name: CI

on:
  push:
    branches: [ "main", "v2", "v3", "dev", "*-*" ]
  pull_request:
    branches: [ "main", "v2", "v3", "dev", "*-*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu2404:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github
  ubuntu2204:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github
  ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github
  ubuntu-obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          build-obfuscate: true
          package: false # Do not try to upload to github
  ubuntu-obfuscate-supply-seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Generate Random Seed
        id: generate_seed
        shell: bash
        run: |
          seed=""
          for i in {1..16}; do
            while true; do  # Loop until an alphanumeric character is generated
              char=$(( (RANDOM % 62) + 48 ))
              if [[ $char -ge 48 && $char -le 57 ]] || [[ $char -ge 65 && $char -le 90 ]] || [[ $char -ge 97 && $char -le 122 ]]; then
                break  # Exit the inner loop if it's alphanumeric
              fi
            done
            seed+="$(printf \\\\$(printf '%o' "$char"))"
          done
          echo "seed=$seed" >> "$GITHUB_OUTPUT"
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          build-obfuscate: true
          build-obfuscate-args: "-literals -tiny -seed=${{ steps.generate_seed.outputs.seed }}"
          package: false # Do not try to upload to github
  macos15arm64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: darwin/universal
          sign: "false"
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          package: false # Do not try to upload to github
#  macos15amd64:
#    runs-on: macos-15-large
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - uses: dAppServer/wails-build-action@main
#        with:
#          build-name: wails
#          build-platform: darwin/universal
#          sign: "false"
#          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
#          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
#          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
#          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
#          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
#          package: false # Do not try to upload to github
  macos14arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: darwin/universal
          sign: "false"
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          package: false # Do not try to upload to github
#  macos14amd64:
#    runs-on: macos-14-large
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - uses: dAppServer/wails-build-action@main
#        with:
#          build-name: wails
#          build-platform: darwin/universal
#          sign: "false"
#          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
#          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
#          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
#          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
#          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
#          package: false # Do not try to upload to github
#  macos13arm64:
#    runs-on: macos-13-xlarge
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - uses: dAppServer/wails-build-action@main
#        with:
#          build-name: wails
#          build-platform: darwin/universal
#          sign: "false"
#          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
#          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
#          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
#          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
#          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
#          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
#          package: false # Do not try to upload to github
  macos13amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails
          build-platform: darwin/universal
          sign: "false"
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          package: false # Do not try to upload to github

  windows2025:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: 'false'
          package: false # Do not try to upload to github
  windows2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: 'false'
          package: false # Do not try to upload to github
  windows2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: 'false'
          package: false # Do not try to upload to github
  windows-nsis:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@33-add-garble-support
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: "true"
          package: false # Do not try to upload to github
